import { NgModule } from '@angular/core';
import {
	MatButtonModule,
	MatIconModule,
	MatFormFieldModule,
	MatInputModule,
	MatDatepickerModule,
	MatNativeDateModule,
	MatCheckboxModule,
	MatCardModule,
	MatSidenavModule,
	MatToolbarModule,
	MatListModule,
	MatTabsModule,
	MatSelectModule,
	MatProgressSpinnerModule,
	MatDialogModule,
	MatTableModule,
	MatSortModule,
	MatPaginatorModule,
	MatGridListModule,
} from '@angular/material';

@NgModule({
	imports: [
		MatButtonModule,
		MatIconModule,
		MatFormFieldModule,
		MatInputModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatCheckboxModule,
		MatCardModule,
		MatSidenavModule,
		MatToolbarModule,
		MatListModule,
		MatTabsModule,
		MatSelectModule,
		MatProgressSpinnerModule,
		MatDialogModule,
		MatTableModule,
		MatSortModule,
		MatPaginatorModule,
		MatGridListModule,
	],
	exports: [
		MatButtonModule,
		MatIconModule,
		MatFormFieldModule,
		MatInputModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatCheckboxModule,
		MatCardModule,
		MatSidenavModule,
		MatToolbarModule,
		MatListModule,
		MatTabsModule,
		MatSelectModule,
		MatProgressSpinnerModule,
		MatDialogModule,
		MatTableModule,
		MatSortModule,
		MatPaginatorModule,
		MatGridListModule,
	]
})
export class MaterialModule { }
